// <auto-generated />
using System;
using Luisde_Prestamos_Cd.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Luisde_Prestamos_Cd.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Luisde_Prestamos_Cd.models.Alquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("codigoCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaAlquiler")
                        .HasColumnType("datetime2");

                    b.Property<int>("noAlquiler")
                        .HasColumnType("int");

                    b.Property<double>("valorAlquiler")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("alquiler");
                });

            modelBuilder.Entity("Luisde_Prestamos_Cd.models.Cd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("codigoTitulo")
                        .HasColumnType("int");

                    b.Property<string>("condicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<int>("noCd")
                        .HasColumnType("int");

                    b.Property<string>("ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("cd");
                });

            modelBuilder.Entity("Luisde_Prestamos_Cd.models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("codigoCliente")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nroDNI")
                        .HasColumnType("int");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temaInteres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("Luisde_Prestamos_Cd.models.DetalleAlquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("codigoTitulo")
                        .HasColumnType("int");

                    b.Property<string>("diasPrestamo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("noAlquiler")
                        .HasColumnType("int");

                    b.Property<int>("noCd")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("detalleAlquiler");
                });

            modelBuilder.Entity("Luisde_Prestamos_Cd.models.Sancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("codigoCliente")
                        .HasColumnType("int");

                    b.Property<int>("noAlquiler")
                        .HasColumnType("int");

                    b.Property<int>("noDiasSancion")
                        .HasColumnType("int");

                    b.Property<int>("noSancion")
                        .HasColumnType("int");

                    b.Property<string>("tipoSancion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("sancion");
                });
#pragma warning restore 612, 618
        }
    }
}
